pipeline{

agent any

stages {
 stage ('Build'){

        steps {
            slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

            script{
            sh "pwd"

            sh "docker build -t helloworld:latest  ./service/"

            }
        }

 }
 stage ('Testing') {

        steps {
          script{


          sh "docker run -d --name ${job_name}_latest -p 5000:5000 helloworld:latest"
          sh "sleep 2"
          sh "curl -X GET http://localhost:5000/techgig/api/hello"
          sh "sleep 1"
          sh "curl -X GET http://localhost:5000/techgig/healthCheck"
          sh "docker stop ${job_name}_latest"
          sh "docker rm ${job_name}_latest"
          sh "docker tag helloworld:latest shubhashish/helloworld:latest"
          sh "docker tag helloworld:latest shubhashish/helloworld:${env.BUILD_ID}"

          }

        }


 }
 stage ('Push'){

        steps {
             script{

                     withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){

                     sh "docker login -u $USERNAME -p $PASSWORD"
                     sh "docker push shubhashish/helloworld:${env.BUILD_ID}"
                     sh "docker push shubhashish/helloworld:latest"
}
          }
        }

 }

stage ('Deploy') {

        agent {
          dockerfile{
            filename 'Dockerfile'
            dir 'service/deployment'

          }
        }
        steps {

            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws']]){
             sh "python service/deployment/deployer.py env=dev region=us-east-1 version=${env.BUILD_ID}"

          }

}
        }



stage ('Cleanup') {
    steps{
        script{


        sh "docker rmi shubhashish/helloworld:${env.BUILD_ID}"
        sh "docker rmi shubhashish/helloworld:latest"


        }

    }

}

}

post {
    success {
      slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

    }

    failure {
      slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

    }
  }


}