pipeline{

agent any

stages {
 stage ('Build'){

        steps {
            script{
            def full_name=env.JOB_NAME.split('/')
            def job_name=full_name[0]
            sh "docker build -t ${job_name}:latest -f Dockerfile hackathon/service/"

            }
        }

 }
 stage ('Testing') {

        steps {
          script{

          def full_name = env.JOB_NAME.split('/')
          def job_name = full_name[0]
          sh "docker run -d --name ${job_name}_latest -p 5000:5000 ${job_name}:latest"
          sh "sleep 2"
          sh "curl -X GET http://localhost:5000/techgig/api/hello"
          sh "sleep 1"
          sh "curl -X GET http://localhost:5000/techgig/healthCheck"
          sh "docker stop ${job_name}_latest"
          sh "docker rm ${job_name}_latest"
          sh "docker tag ${job_name}:latest shubhashish/${job_name}:latest"
          sh "docker tag ${job_name}:latest shubhashish/${job_name}:${env.BUILD_ID}"

          }

        }


 }
 stage ('Push'){

        steps {
             script{
                     def full_name = env.JOB_NAME.split('/')
                     def job_name = full_name[0]
                     withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){

                     sh "docker login -u $USERNAME -p $PASSWORD"
                     sh "docker push shubhashish/${job_name}:${env.BUILD_ID}"
}
          }
        }

 }

stage ('Deploy') {

        agent {
          dockerfile{
            filename 'Dockerfile'
            dir 'service/deployment'

          }
        }
        steps {

            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws']]){
             sh "python deployment/deployer.py env=dev access_id=$USERNAME access_key=$PASSWORD region=us-east-1 version=${env.BUILD_ID}"

          }

}
        }



stage ('Cleanup') {
    steps{
        script{
        def full_name = env.JOB_NAME.split('/')
        def job_name = full_name[0]


        sh "docker rmi shubhashish/${job_name}:${env.BUILD_ID}"
        sh "docker rmi shubhashish/${job_name}:latest"


        }

    }

}

}


}