pipeline{

agent any
parameters {
        string(name: 'stack', defaultValue: 'dev', description: 'Name of the stack')
    }

stages {

   stage('${env.JOB_NAME}'){
   steps {
             script{

                     withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws']]){
                     sh "export AWS_DEFAULT_REGION=us-east-1"
                     sh "aws cloudformation ${env.JOB_NAME} --stack-name dev --template-body file://stack/infrastructure.yaml"
}
          }


 }}}}