pipeline{

agent any

stages {

   stage('create'){
   steps {
             script{

                     withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws']]){
                     sh "export AWS_DEFAULT_REGION=us-east-1"
                     sh "aws s3 ls"
}
          }


 }}}}